<x-app-layout><x-slot name="header"><h2 class="font-semibold text-xl text-slate-800">Create Employee</h2></x-slot><div class="max-w-3xl mx-auto px-4 py-6"><form method="POST" action="{{ route('employees.store') }}" class="space-y-4 bg-white p-6 border rounded">@csrf
<label class="block text-sm font-medium">Employee Code</label><input name="employee_code" class="w-full border rounded p-2">
<div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium">First Name</label><input name="first_name" class="border rounded p-2 w-full"></div><div><label class="block text-sm font-medium">Last Name</label><input name="last_name" class="border rounded p-2 w-full"></div></div>
<label class="block text-sm font-medium">Email</label><input name="email" class="w-full border rounded p-2">
<label class="block text-sm font-medium">Department</label><select name="department_id" class="w-full border rounded p-2">@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select>
<label class="block text-sm font-medium">Job Position</label><select name="job_position_id" class="w-full border rounded p-2">@foreach($jobPositions as $position)<option value="{{ $position->id }}">{{ $position->title }}</option>@endforeach</select>
<label class="block text-sm font-medium">Employment Status</label><select name="employment_status" class="w-full border rounded p-2"><option value="active">active</option><option value="probationary">probationary</option><option value="regular">regular</option><option value="on_leave">on_leave</option><option value="resigned">resigned</option><option value="terminated">terminated</option></select>
<div class="grid grid-cols-3 gap-4"><div><label class="block text-sm font-medium">Basic Salary</label><input name="basic_salary" type="number" step="0.01" class="border rounded p-2 w-full"></div><div><label class="block text-sm font-medium">Daily Rate</label><input name="daily_rate" type="number" step="0.01" class="border rounded p-2 w-full"></div><div><label class="block text-sm font-medium">Hourly Rate</label><input name="hourly_rate" type="number" step="0.01" class="border rounded p-2 w-full"></div></div>
<button class="px-3 py-2 bg-slate-900 text-white rounded">Save</button></form></div></x-app-layout>
